version: '3'
services:
  taxi-socket:
    build: ./taxi_socket 
    ports:
      - "5557:5557"
    volumes:
      - ../data/:/app/data/
    environment: 
      - OFFSET=$OFFSET 
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    depends_on:
      - taxi-socket
    volumes:
      - ../dags:/app
      - ./h3_pyspark.zip:/app/h3_pyspark.zip
      - ../data/nyc_taxi_zones_h3_10.parquet.gzip:/app/data/nyc_taxi_zones_h3_10.parquet.gzip
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - PYSPARK_PYTHON=python3
      - SPARK_HOME=/spark
  spark-worker-1:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-worker-1
    volumes:
      - ../dags:/app
      - ./h3_pyspark.zip:/app/h3_pyspark.zip
      - ../data/nyc_taxi_zones_h3_10.parquet.gzip:/app/data/nyc_taxi_zones_h3_10.parquet.gzip
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - PYSPARK_PYTHON=python3
      - SPARK_HOME=/spark

networks:
  default:
    external:
      name: serasa
